### ISSUE TITLE
pritterWidth 修正为 100个字符

### ISSUE THREAD

**Issue by mumiao** [DTStack/ko#105]
之前投票，很多同学对这个字段意识不深，目前大部分组件Props因为一个字符不能超过200个，导致代码很难阅读，跟离线以及部分同学协商以及测试，控制到一行100个字符

**Comment by mumiao** [comment]
解决完尽快发个包，方便同学使用升级

**Comment by liuxy0551** [comment]
已更新到 global/feat_ko_6.0
