### ISSUE TITLE
[bug] overlarge cache folder in node_modules

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/ko#116]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/18719701/218997414-63c6f22a-b35f-4eeb-a8dd-0379fb0c91e3.png">

**Comment by LuckyFBB** [comment]
.cache文件过大问题，本地复现publicService半个月产生了30G的缓存，ko默认开启了webpack的filesystem缓存，cache的maxAge配置项并不会对缓存进行清除操作，关联issues[#13291](https://github.com/webpack/webpack/issues/13291) , 考虑写个plugin进行缓存清除

**Comment by mumiao** [comment]
done
