### ISSUE TITLE
logLevel配置项是无效的，webpack stats无法应用在NodeAPI中

### ISSUE THREAD

**Issue by JackWang032** [DTStack/ko#131]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/64318393/233608510-9936da2f-fb18-444b-afee-a37fbae30e34.png">

<img width="840" alt="image" src="https://user-images.githubusercontent.com/64318393/233608641-4b36b4d5-a783-43f2-acc1-1c9f5ade9a30.png">

**Comment by LuckyFBB** [comment]
使用 Node 启动 webpack 项目时。

对于 Stats 来说，在 webpack-dev-server 中是可以直接使用 stats 属性来配置相关的信息展示。

但是在 webpack 中，无法通过配置来展示信息，只能够通过通过 webpack 回调来做的
```js
webpack(config, (error, stats: any) => {
  if (stats && stats.hasErrors()) {
    throw stats.toString({
      logging: 'error',
      colors: true,
    });
  }
});
```

**Comment by LuckyFBB** [comment]
done
