### ISSUE TITLE
暴露 webpack 给自定义 plugin 使用

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ko#138]
我们支持可以自定义 plugin 通过 config 配置传递给 ko，例如：
![image](https://github.com/DTStack/ko/assets/38368040/6f7f4f67-07c6-4094-a495-0b1b8c995d16)

但是对于 webpack 来说，ko 尚未暴露出来，我们产品又尚未直接安装 webpack，因此我们下述的引入是一种幽灵依赖
![image](https://github.com/DTStack/ko/assets/38368040/ffa84fd6-ea00-42c2-97ae-d4c90b74a68c)

因此想要 ko 给 plugin 暴露 webpack 来使用

**Comment by mumiao** [comment]
done
