### ISSUE TITLE
Compatible with YARN2 with PNP

### ISSUE THREAD

**Issue by ProfBramble** [DTStack/ko#25]
这是一个可选的功能，使用者可以自行决定是否使用yarn2 with PnP

脚手架可以为用户支持PnP做一些前置工作，比如预装 [ pnp-webpack-plugin](https://github.com/arcanis/pnp-webpack-plugin) 。（目前 `create-react-app` [已经实装](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L67)）

支持PnP的大致好处如下： 
- 依赖0安装，拉下项目代码就可以直接 `yarn start`
- CI 跳过最慢的依赖安装，直接进行后续的`check-type` `test`等操作，大大提升效率
- 依赖变更在`code review`的时候非常清楚

详情可见我最近写的 [Yarn2 with PnP 升级指北](https://github.com/ProfBramble/treasure-bucket/blob/main/tools/Yarn2withPnP.md)

**Comment by ProfBramble** [comment]
可能 pnpm 确实是更好的选择

**Comment by xbrave** [comment]
will change to pnpm
