### ISSUE TITLE
RFC: upgrade package management tool

### ISSUE THREAD

**Issue by AttackOnMorty** [DTStack/ko#26]
For ko project, we can replace `npm` with `Yarn`. Yarn has better performance over npm. Also, we can add `preinstall` script to force using `Yarn`.

Reference: https://github.com/DTStack/devops/tree/main/force-using-yarn-and-lock-version

**Comment by xbrave** [comment]
This enhence feature will be supoorted in next offfical release

**Comment by xbrave** [comment]
done
