### ISSUE TITLE
fix same folder name bug

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ko#85]
get a error when my project components folder name same as dt-common components folder name

my project
![image](https://user-images.githubusercontent.com/38368040/158809817-32e0f8fb-64c1-4b0a-a962-e92f171c9e3d.png)

dt-common
![image](https://user-images.githubusercontent.com/38368040/158809907-7a9fb8dd-c008-4059-adbf-9feaacafd7e2.png)

error
![image](https://user-images.githubusercontent.com/38368040/158809646-57006cea-1d41-437e-9aeb-072d16fecb19.png)

**Comment by xbrave** [comment]
主要应该是webpack[resolve](https://webpack.js.org/configuration/resolve/#root)相关的配置，具体可以参考studio的自定义[resolve plugins](https://webpack.js.org/configuration/resolve/#resolveplugins)

**Comment by LuckyFBB** [comment]
尚未复现该问题
