### ISSUE TITLE
antd3.x button ghost style error

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/ko#94]
描述：
antd 3.x button 使用 ghost 属性，打包部署后样式优先级错乱，本地启动没问题

className：
ant-btn-background-ghost  
ant-btn-background-ghost:hover

<img width="787" alt="image" src="https://user-images.githubusercontent.com/34759874/168944901-4336ded1-8217-4cb6-be00-3441e959da3f.png">

**Comment by xbrave** [comment]
和 #95 归属于同一类问题，css minimizer相关的plugin并不能保证样式引入顺序，建议样式统一管理且明确划分，目前依赖的dt-common,RC, antd等样式并不是特别规范

**Comment by mumiao** [comment]
- API:
  原因：main文件导入顺序太靠前了，规范了main和基础css的导入顺序，解决了 
  reference： 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/22880945/204736409-76757eea-93f3-4d29-96d7-dc39de1e8713.png">

- Tag:
  目前在复现排查中

**Comment by mumiao** [comment]
done，目前依赖的dt-common,RC, antd等样式并不是特别规范, 确实是应用库样式管理的问题
Please Documentation:  https://dtstack.yuque.com/rd-center/sm6war/mx21k7f4ydxq4xbf
